src/main/java/it/r8/webapp/pepmg/freelancer/FreeLancersListController.java
package it.r8.webapp.pepmg.freelancer;

import java.util.List;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.inject.Inject;

import it.r8.webapp.pepmg.core.Repository;

@ManagedBean
@ApplicationScoped
public class FreeLancersListController {

	private String test;
	
	@Inject
	private Repository<Integer,FreeLancer> freeLancerRepository;

	public String getTest() {
		return test;
	}

	public void setTest(String test) {
		this.test = test;
	}

	public List<FreeLancer> getFreeLancers() {
		return freeLancerRepository.getAll();
	}
}

src/main/webapp/pages/customers/addc.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>
	<title>Strategy, Consulting, Digital | Project &amp; Planning</title>
</h:head>
<h:body style="padding-top: 60px">
        <b:navBar brand="" brandHref="#" inverse="true" fixed="top" fluid="true">
            <h:graphicImage value="../logo1.png" />
            <b:navbarLinks pull="right">
                <b:navLink value="Visualizza lista" href="http://localhost:8080/PePMG/pages/customers/listc.xhtml?typeCompany=1"></b:navLink>
                <b:navLink value="Index" href="http://localhost:8080/PePMG/pages/index.xhtml"></b:navLink>
            </b:navbarLinks>
        </b:navBar>
        
        <b:container fluid="true">
            <b:row>
                <b:column col-sm="3" col-md="2" styleClass="sidebar">
                    <b:listLinks>
                        <b:navLink header="" />
                        <b:dropButton look="primary" value="Fornitore">
  						<b:navLink value="Azienda" href="http://localhost:8080/PePMG/pages/customers/listc.xhtml?typeCompany=1"></b:navLink> 
  						<b:navLink value="Libero Professionista" href="http://localhost:8080/PePMG/pages/customers/listf.xhtml"></b:navLink>
   						</b:dropButton>
                        </b:listLinks>
                    <b:listLinks>
                        <b:dropButton look="primary" value="Cliente">
                        <b:navLink value="Azienda" href="http://localhost:8080/PePMG/pages/customers/listc.xhtml?typeCompany=0"></b:navLink>
                        <b:navLink value="Libero Professionista" href="http://localhost:8080/PePMG/pages/customers/listf.xhtml"></b:navLink>
                        </b:dropButton>
                        </b:listLinks>
                </b:column>
                
        <b:column col-xs="9" col-md="10" styleClass="show-grid">        
		<h:form>
			<h:panelGrid columns="1">
		
				<h:inputHidden id="id" value="#{companyAddController.company.id}" />
				
				<h:outputLabel value="Nome azienda:" for="businessName" />
				<h:inputText id="businessName" value="#{companyAddController.company.businessName}" />
				<h:message for="businessName" style="color:red" />

				<h:outputLabel value="E-Mail:" for="email" />
				<h:inputText id="email" value="#{companyAddController.company.email}" />
				<h:message for="email" style="color:red" />
				
				<h:outputLabel value="Telefono:" for="telephone" />
				<h:inputText id="telephone" value="#{companyAddController.company.telephone}" />
				<h:message for="telephone" style="color:red" />

				<h:outputLabel value="Partita Iva:" for="iva" />
				<h:inputText id="iva" value="#{companyAddController.company.iva}" />
				<h:message for="iva" style="color:red" />

				<h:outputLabel value="Referente amministrativo:" for="ceo" />
				<h:inputText id="ceo" value="#{companyAddController.company.ceo}" />
				<h:message for="ceo" style="color:red" />

				<h:outputLabel value="Referente di progetto:" for="projectManager" />
				<h:inputText id="projectManager" value="#{companyAddController.company.projectManager}" />
				<h:message for="projectManager" style="color:red" />
				
				<h:outputLabel value="Indirizzo sede legale:" for="legalAddress" />
				<h:inputText id="legalAddress" value="#{companyAddController.company.legalAddress}" />
				<h:message for="legalAddress" style="color:red" />
				
				<h:outputLabel value="Indirizzo sede operativa:" for="headQuarter" />
				<h:inputText id="headQuarter" value="#{companyAddController.company.headQuarter}" />
				<h:message for="headQuarter" style="color:red" />
				
				<h:outputLabel value="Fascia:" for="area" />
				<h:inputText id="area" value="#{companyAddController.company.area}" />
				<h:message for="area" style="color:red" />
				
				<h:outputLabel value="Categoria:" for="category" />
				<h:inputText id="category" value="#{companyAddController.company.category}" />
				<h:message for="category" style="color:red" />
				
				<h:outputLabel value="Qualifica iso 9000:" for="qualified" />
				<h:inputText id="qualified" value="#{companyAddController.company.qualified}" />
				<h:message for="qualified" style="color:red" />

			</h:panelGrid>
			<br/>
			
			<h:commandButton value="submit" action="#{companyAddController.addCompany}">
				<f:ajax execute="@form" render="@form" />
			</h:commandButton>
		</h:form>
		</b:column>
		</b:row>
	</b:container>
	<style type="text/css">
        .sub-header {
            border-bottom: 1px solid #f5f5f5;
            padding-bottom: 10px;
        }
        .navbar-fixed-top {
            border: 0 none;
            background: #034A88;
        }
        .sidebar {
            height: 100%;
        }
        .nav-list {
            margin-bottom: 20px;
            margin-left: -20px;
            margin-right: -21px;
        }
        .nav-list > li > a {
            padding-left: 20px;
            padding-right: 20px;
        }
        .nav-list > .active > a, .nav-sidebar > .active > a:hover, .nav-sidebar > .active > a:focus {
            background-color: #428bca;
            color: #fff;
        }
        .main {
            padding: 20px;
        }
        @media (min-width: 768px) {
        .main {
            padding-left: 40px;
            padding-right: 40px;
        }
        }
        .main .page-header {
            margin-top: 0;
        }
        .placeholders {
            margin-bottom: 30px;
            text-align: center;
        }
        .placeholders h4 {
            margin-bottom: 0;
        }
        .placeholder {
            margin-bottom: 20px;
        }
        .placeholder img {
            border-radius: 50%;
            display: inline-block;
        }
        </style>
	</h:body>
</html>

src/main/webapp/pages/customers/addf.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>
	<title>Strategy, Consulting, Digital | Project &amp; Planning</title>
</h:head>
<h:body style="padding-top: 60px">
        <b:navBar brand="" brandHref="#" inverse="true" fixed="top" fluid="true">
            <h:graphicImage value="../logo1.png" />
            <b:navbarLinks pull="right">
                <b:navLink value="Visualizza lista" href="http://localhost:8080/PePMG/pages/customers/listf.xhtml"></b:navLink>
                <b:navLink value="Index" href="http://localhost:8080/PePMG/pages/index.xhtml"></b:navLink>
                <b:navLink value="Help" href="#"></b:navLink>
            </b:navbarLinks>
        </b:navBar>
        
        <b:container fluid="true">
            <b:row>
                <b:column col-sm="3" col-md="2" styleClass="sidebar">
                    <b:listLinks>
                        <b:navLink header="" />
                        <b:dropButton look="primary" value="Fornitore">
  						<b:navLink value="Azienda" href="http://localhost:8080/PePMG/pages/customers/listc.xhtml"></b:navLink> 
  						<b:navLink value="Libero Professionista" href="http://localhost:8080/PePMG/pages/customers/listf.xhtml"></b:navLink>
   						</b:dropButton>
                        </b:listLinks>
                    <b:listLinks>
                        <b:dropButton look="primary" value="Cliente">
                        <b:navLink value="Azienda" href="http://localhost:8080/PePMG/pages/customers/listc.xhtml"></b:navLink>
                        <b:navLink value="Libero Professionista" href="http://localhost:8080/PePMG/pages/customers/listf.xhtml"></b:navLink>
                        </b:dropButton>
                        </b:listLinks>
                </b:column>
                
        <b:column col-xs="9" col-md="10" styleClass="show-grid">        
		<h:form>
			<h:panelGrid columns="1">
		
				<h:inputHidden id="id" value="#{freeLancerAddController.freeLancer.id}" />
				
				<h:outputLabel value="Nome:" for="name" />
				<h:inputText id="name" value="#{freeLancerAddController.freeLancer.name}" />
				<h:message for="name" style="color:red" />

				<h:outputLabel value="Cognome:" for="surname" />
				<h:inputText id="surname" value="#{freeLancerAddController.freeLancer.surname}" />
				<h:message for="surname" style="color:red" />

				<h:outputLabel value="Codice Fiscale:" for="fiscalCode" />
				<h:inputText id="fiscalCode" value="#{freeLancerAddController.freeLancer.fiscalCode}" />
				<h:message for="fiscalCode" style="color:red" />
				
				<h:outputLabel value="Partita Iva:" for="iva" />
				<h:inputText id="iva" value="#{freeLancerAddController.freeLancer.iva}" />
				<h:message for="iva" style="color:red" />
				
				<h:outputLabel value="E-Mail:" for="email" />
				<h:inputText id="email" value="#{freeLancerAddController.freeLancer.email}" />
				<h:message for="email" style="color:red" />
				
				<h:outputLabel value="Telefono:" for="telephone" />
				<h:inputText id="telephone" value="#{freeLancerAddController.freeLancer.telephone}" />
				<h:message for="telephone" style="color:red" />
				
				<h:outputLabel value="Indirizzo:" for="address" />
				<h:inputText id="address" value="#{freeLancerAddController.freeLancer.address}" />
				<h:message for="address" style="color:red" />
				
				<h:outputLabel value="Città:" for="city" />
				<h:inputText id="city" value="#{freeLancerAddController.freeLancer.city}" />
				<h:message for="city" style="color:red" />
				
				<h:outputLabel value="Regione:" for="district" />
				<h:inputText id="district" value="#{freeLancerAddController.freeLancer.district}" />
				<h:message for="district" style="color:red" />

			</h:panelGrid>
			<br/>
			<h:commandButton value="submit" action="#{freeLancerAddController.addFreeLancer}">
				<f:ajax execute="@form" render="@form" />
			</h:commandButton>
		</h:form>
		</b:column>
		</b:row>
	</b:container>
	<style type="text/css">
        .sub-header {
            border-bottom: 1px solid #f5f5f5;
            padding-bottom: 10px;
        }
        .navbar-fixed-top {
            border: 0 none;
            background: #034A88;
        }
        .sidebar {
            height: 100%;
        }
        .nav-list {
            margin-bottom: 20px;
            margin-left: -20px;
            margin-right: -21px;
        }
        .nav-list > li > a {
            padding-left: 20px;
            padding-right: 20px;
        }
        .nav-list > .active > a, .nav-sidebar > .active > a:hover, .nav-sidebar > .active > a:focus {
            background-color: #428bca;
            color: #fff;
        }
        .main {
            padding: 20px;
        }
        @media (min-width: 768px) {
        .main {
            padding-left: 40px;
            padding-right: 40px;
        }
        }
        .main .page-header {
            margin-top: 0;
        }
        .placeholders {
            margin-bottom: 30px;
            text-align: center;
        }
        .placeholders h4 {
            margin-bottom: 0;
        }
        .placeholder {
            margin-bottom: 20px;
        }
        .placeholder img {
            border-radius: 50%;
            display: inline-block;
        }
        </style>
	</h:body>
</html>

src/main/webapp/pages/customers/css.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
      
    <h:head>
        <title>Strategy, Consulting, Digital | Project &amp; Planning</title>
    </h:head>
    
    <h:body style="padding-top: 60px">
        <b:navBar brand="" brandHref="#" inverse="true" fixed="top" fluid="true">
            <h:graphicImage value="logo.bmp" />
            <b:navbarLinks pull="right">
                <b:navLink value="Dashboard" href="#"></b:navLink>
                <b:navLink value="Settings" href="#"></b:navLink>
                <b:navLink value="Profile" href="#"></b:navLink>
                <b:navLink value="Help" href="#"></b:navLink>
            </b:navbarLinks>
        </b:navBar>
        
        <b:container fluid="true">
            <b:row>
                <b:column col-sm="3" col-md="2" styleClass="sidebar">
                    <b:listLinks>
                        <b:navLink header="" />
                        <b:dropButton look="primary" value="Fornitore">
  						<b:navLink value="Azienda" href="http://localhost:8080/PePMG/pages/customers/listc.xhtml"></b:navLink> 
  						<b:navLink value="Libero Professionista" href="http://localhost:8080/PePMG/pages/customers/listf.xhtml"></b:navLink>
   						</b:dropButton>
                        </b:listLinks>
                    <b:listLinks>
                        <b:dropButton look="primary" value="Cliente">
                        <b:navLink value="Azienda" href="http://localhost:8080/PePMG/pages/customers/listc.xhtml"></b:navLink>
                        <b:navLink value="Libero Professionista" href="http://localhost:8080/PePMG/pages/customers/listf.xhtml"></b:navLink>
                        </b:dropButton>
                        </b:listLinks>
                </b:column>
                
                
                
                
                <b:column>
             
          
          
          
               
               
               
               
               </b:column> 
            
            
            
            
            
            
            </b:row>
        </b:container> 
        <style type="text/css">
        .sub-header {
            border-bottom: 1px solid #f5f5f5;
            padding-bottom: 10px;
        }
        .navbar-fixed-top {
            border: 0 none;
            background: #034A88;
        }
        .sidebar {
            display: none;
        }
        @media (min-width: 768px) {
        .sidebar {
            background-color: #f5f5f5;
            border-right: 1px solid #eee;
            bottom: 0;
            display: block;
            left: 0;
            overflow-x: hidden;
            overflow-y: auto;
            padding: 20px;
            position: fixed;
            top: 51px;
            z-index: 1000;
        }
        }
        .nav-list {
            margin-bottom: 20px;
            margin-left: -20px;
            margin-right: -21px;
        }
        .nav-list > li > a {
            padding-left: 20px;
            padding-right: 20px;
        }
        .nav-list > .active > a, .nav-sidebar > .active > a:hover, .nav-sidebar > .active > a:focus {
            background-color: #428bca;
            color: #fff;
        }
        .main {
            padding: 20px;
        }
        @media (min-width: 768px) {
        .main {
            padding-left: 40px;
            padding-right: 40px;
        }
        }
        .main .page-header {
            margin-top: 0;
        }
        .placeholders {
            margin-bottom: 30px;
            text-align: center;
        }
        .placeholders h4 {
            margin-bottom: 0;
        }
        .placeholder {
            margin-bottom: 20px;
        }
        .placeholder img {
            border-radius: 50%;
            display: inline-block;
        }
        </style>
    </h:body>
</html>

src/main/webapp/pages/customers/listc.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
	<title>Strategy, Consulting, Digital | Project &amp; Planning</title>
</h:head>

<h:body style="padding-top: 60px">
	<span>#{companyListController.typeCompany == 0 ? 'Cliente' :'Fornitore'}</span>
	<b:navBar brand="" brandHref="#" inverse="true" fixed="top"
		fluid="true">
		<h:graphicImage value="../logo1.png" href="#"/> 
		<b:navbarLinks pull="right">
			<b:navLink value="Aggiungi" href="http://localhost:8080/PePMG/pages/customers/addc.xhtml?typeCompany=1"></b:navLink>
                <b:navLink value="Index" href="http://localhost:8080/PePMG/pages/index.xhtml"></b:navLink>
		</b:navbarLinks>
	</b:navBar>

	<b:container fluid="true">
		<b:row>
			<b:column col-xs="3" col-md="2" styleClass="sidebar">
				<b:listLinks>
					<b:navLink header="" />
					<b:dropButton look="primary" value="Fornitore">
						<b:navLink value="Azienda"
							href="http://localhost:8080/PePMG/pages/customers/listc.xhtml?typeCompany=1"></b:navLink>
						<b:navLink value="Libero Professionista"
							href="http://localhost:8080/PePMG/pages/customers/listf.xhtml?typeCompany=1"></b:navLink>
					</b:dropButton>
				</b:listLinks>
				<b:listLinks>
					<b:dropButton look="primary" value="Cliente">
						<b:navLink value="Azienda"
							href="http://localhost:8080/PePMG/pages/customers/listc.xhtml?typeCompany=0"></b:navLink>
						<b:navLink value="Libero Professionista"
							href="http://localhost:8080/PePMG/pages/customers/listf.xhtml?typeCompany=0"></b:navLink>
					</b:dropButton>
				</b:listLinks>
			</b:column>

			<b:column col-xs="9" col-md="10" styleClass="show-grid">
				<h:form>
					<b:dataTable value="#{companyListController.companies}"
						var="company">

						<b:dataTableColumn label="Nome azienda" value="#{company.businessName}" />
						<b:dataTableColumn label="E-Mail" value="#{company.email}" />
						<b:dataTableColumn label="Telefono" value="#{company.telephone}" />
						<b:dataTableColumn label="Indirizzo sede legale" value="#{company.legalAddress}" />
						<b:dataTableColumn label="Indirizzo sede operativa" value="#{company.headQuarter}" >
						

							<b:pillLinks>
								<b:commandButton iconAwesome="fa-trash-o"
									styleClass="btn btn-primary"
									action="#{companyDeleteController.deleteCompany(company.id)}" />
								<b:navLink iconAwesome="fa-external-link" active="true"
									href="http://localhost:8080/PePMG/pages/customers/addc.xhtml?id=${company.id}" />
							</b:pillLinks>
						</b:dataTableColumn>
					</b:dataTable>
				</h:form>
				
			</b:column>
		</b:row>
	</b:container>

	<style type="text/css">
.sub-header {
	border-bottom: 1px solid #f5f5f5;
	padding-bottom: 10px;
}

.navbar-fixed-top {
	border: 0 none;
	background: #034A88;
}

.sidebar {
	height: 100%;
}

.nav-list {
	margin-bottom: 20px;
	margin-left: -20px;
	margin-right: -21px;
}

.nav-list>li>a {
	padding-left: 20px;
	padding-right: 20px;
}

.nav-list>.active>a, .nav-sidebar>.active>a:hover, .nav-sidebar>.active>a:focus
	{
	background-color: #428bca;
	color: #fff;
}

.main {
	padding: 20px;
}

@media ( min-width : 768px) {
	.main {
		padding-left: 40px;
		padding-right: 40px;
	}
}

.main .page-header {
	margin-top: 0;
}

.placeholders {
	margin-bottom: 30px;
	text-align: center;
}

.placeholders h4 {
	margin-bottom: 0;
}

.placeholder {
	margin-bottom: 20px;
}

.placeholder img {
	border-radius: 50%;
	display: inline-block;
}
</style>
</h:body>
</html>

src/main/webapp/pages/customers/listf.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>
	<title>Strategy, Consulting, Digital | Project &amp; Planning</title>
</h:head>
<h:body style="padding-top: 60px">
		<span>#{companyListController.typeCompany == 0 ? 'Fornitore' : 'Cliente'}</span>
        <b:navBar brand="" brandHref="#" inverse="true" fixed="top" fluid="true">
            <h:graphicImage value="../logo1.png"/>
            <b:navbarLinks pull="right">
                
                <b:navLink value="Aggiungi" href="http://localhost:8080/PePMG/pages/customers/addf.xhtml"></b:navLink>
                <b:navLink value="Index" href="http://localhost:8080/PePMG/pages/index.xhtml"></b:navLink>
                
                
            </b:navbarLinks>
    	</b:navBar>
		  <b:container fluid="true">
            <b:row>
                <b:column col-xs="3" col-md="2" styleClass="sidebar">
                    <b:listLinks>
                        <b:navLink header="" />
                        <b:dropButton look="primary" value="Fornitore">
  						<b:navLink value="Azienda" href="http://localhost:8080/PePMG/pages/customers/listc.xhtml"></b:navLink> 
  						<b:navLink value="Libero Professionista" href="http://localhost:8080/PePMG/pages/customers/listf.xhtml"></b:navLink>
   						</b:dropButton>
                        </b:listLinks>
                    <b:listLinks>
                        <b:dropButton look="primary" value="Cliente">
                        <b:navLink value="Azienda" href="http://localhost:8080/PePMG/pages/customers/listc.xhtml"></b:navLink>
                        <b:navLink value="Libero Professionista" href="http://localhost:8080/PePMG/pages/customers/listf.xhtml"></b:navLink>
                        </b:dropButton>
                        </b:listLinks>
                </b:column >
                
                
             <b:column col-xs="9" col-md="10" styleClass="show-grid">
					<h:form>   
                
			<b:dataTable value="#{freeLancersListController.freeLancers}" var="freeLancer">
				<b:dataTableColumn label = "Nome" value="#{freeLancer.name}"  />
				<b:dataTableColumn label = "Cognome" value="#{freeLancer.surname}"  />
				
				
				<b:dataTableColumn label = "E-Mail" value="#{freeLancer.email}" />
				<b:dataTableColumn label = "Telefono" value="#{freeLancer.telephone}"  />
				<b:dataTableColumn label = "Indirizzo" value="#{freeLancer.address}" />
				
				
				
				
				
				
				
				
				<b:dataTableColumn label = " ">
       				<b:pillLinks>
       				
       				
       				
       					<b:commandButton iconAwesome="fa-trash-o" styleClass="btn btn-primary" action="#{freeLancerDeleteController.deleteFreeLancer(freeLancer.id)}"/>
						<b:navLink iconAwesome="fa-external-link"  active="true" href="http://localhost:8080/PePMG/pages/customers/addf.xhtml?id=${freeLancer.id}"/>
					</b:pillLinks>	
         		</b:dataTableColumn >	
						</b:dataTable>
					</h:form>
						
				</b:column>
				</b:row>
	</b:container>
	
	<style type="text/css">
        .sub-header {
            border-bottom: 1px solid #f5f5f5;
            padding-bottom: 10px;
        }
        .navbar-fixed-top {
            border: 0 none;
            background: #034A88;
        }
        .sidebar {
            height: 100%;
        }
        .nav-list {
            margin-bottom: 20px;
            margin-left: -20px;
            margin-right: -21px;
        }
        .nav-list > li > a {
            padding-left: 20px;
            padding-right: 20px;
        }
        .nav-list > .active > a, .nav-sidebar > .active > a:hover, .nav-sidebar > .active > a:focus {
            background-color: #428bca;
            color: #fff;
        }
        .main {
            padding: 20px;
        }
        @media (min-width: 768px) {
        .main {
            padding-left: 40px;
            padding-right: 40px;
        }
        }
        .main .page-header {
            margin-top: 0;
        }
        .placeholders {
            margin-bottom: 30px;
            text-align: center;
        }
        .placeholders h4 {
            margin-bottom: 0;
        }
        .placeholder {
            margin-bottom: 20px;
        }
        .placeholder img {
            border-radius: 50%;
            display: inline-block;
        }
        </style>
	</h:body>
</html>